# -*- coding: utf-8 -*-
"""differentfunctions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBFf55a-D-eWNQXWNW03Rw5HFuXrIQ-1
"""

class differentfunctions():

        def Subfields():
          lists=["Machine Learning","Neural Networks","Vision,Robotics","Speech Processing","Natural Language Processing"]
          print("Sub-fields in AI are:")

          for i in lists:
            print(i)


        def Eligible():
                  gender = input("Your Gender: ")
                  age = int(input("Your Age: "))

                  if((gender == "Male" and age >= 21) or
                    (gender == "Female" and age >= 18)):
                      print("ELIGIBLE")
                  else:
                      print("NOT ELIGIBLE")

        def percentage():
            Subject1=int(input("Subject1="))
            Subject2=int(input("Subject2="))
            Subject3=int(input("Subject3="))
            Subject4=int(input("Subject4="))
            Subject5=int(input("Subject5="))
            total=Subject1+Subject2+Subject3+Subject4+Subject5
            print("Total:",total)
            percentage=(total/500)*100
            print("Percentage:",percentage)

        def triangle():
            Height=int(input("Height:"))
            Breadth=int(input("Breadth:"))
            area= (Height*Breadth)/2
            print("Area of Triangle:",area)
            Height1=int(input("Height1:"))
            Height2=int(input("Height2:"))
            Breadth=int(input("Breadth:"))
            perimeter=Height1+Height2+Breadth
            print("Perimeter of Triangle:",perimeter)