# -*- coding: utf-8 -*-
"""Python debug -set 2-.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5YBNIiqQSc4hex2LRzM38stYQM_iCDU
"""

#1.Find the error in the following Python code:
import math
print(math.sqrt(16))

#2.Find the error in the following Python code:
def my_function():
    global x
    x += 5
    print(x)

x = 10
my_function()

#3.x = 5

if (x == 10):
    print("x is 10")

#4.

numbers = [5, 3, 8, 2]
numbers.sort()
print(numbers)

#5.
def square(n):
    return n * n

print(square(4))

#6.
my_tuple = (1, 5, 3)

## because tuples are immutable

#7.
name = "Alice"
age = 25
print("My name is %s and I am %d years old" % (name,age))

#8.
a = [1, 2, 3]
b = [1, 2, 3]
if a == b:
    print("Lists are equal")

#9.
for i in range(5, 1,-1):
    print(i)

#10.
student = {"name": "John", "age": 20}
print(student["name"])