# -*- coding: utf-8 -*-
"""multipleFunctions.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTKR2TOAy9shaRDMJCZHuZqeKt30uD6Q
"""

class multiplefunction():

      def oddeven():
         num=int(input("Enter the number:"))
         if((num%2)==1):
          print("Odd number")
          message="Odd Number"
         else:
          print("Even number")
          message="Even Number"
         return message

      def BMI():
        BMI_index=float(input("Enter the BMI Index:"))
        if(BMI_index<18.5):
          print("Under weight")
          message="Under weight"
        elif(BMI_index<24.9):
          print("Healthy weight")
          message="Healthy weight"
        elif(BMI_index<35):
          print("Overweight")
          message="Overweight"
        else:
          print("Higher weight status")
          message="Higher weight status"
        return message